name: Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go 1.24.1
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.1'
      - name: build
        run: cd ./cli/alphabill && go build -o ../../build/alphabill

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go 1.24.1
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.1'
      - name: vet
        run: go vet ./...
      - name: test
        run: go test ./... -coverpkg=./... -count=1 -coverprofile test-coverage.out

  analyze:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go 1.24.1
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.1'
      - name: Install gosec
        run: go install github.com/securego/gosec/v2/cmd/gosec@latest
      - name: gosec
        run: gosec -fmt=sonarqube -out gosec_report.json -no-fail ./...
