name: Test

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup Go 1.24.1
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.1'
      - name: Test
        run: go test ./... -coverpkg=./... -count=1 -coverprofile test-coverage.out

